csutils/csmock

scripts/chroot-fixups/openssl-public-header-files.sh
... about unused return values of functions that may start to fail after update of openssl or the system crypto policy.
=> chroot-fixups/openssl-public-header-files.sh: enable warnings

scripts/chroot-fixups/openssl-public-header-files.sh
... as proposed in https://github.com/openssl/openssl/pull/15905 in case openssl-3.0 is installed in the buildroot.
=> scripts/chroot-fixups/openssl-public-header-files.sh: patch `<openssl/evp.h>`

make-srpm.sh, py/csmock, py/plugins/bandit.py, py/plugins/clang.py, py/plugins/cppcheck.py, py/plugins/gcc.py, py/plugins/pylint.py, py/plugins/shellcheck.py, py/plugins/smatch.py, py/plugins/strace.py, py/plugins/valgrind.py
Instead of assigning unique numbers to each plug-in, let them define
relative dependencies via the "pass_before" and "pass_after" attributes
of PluginProps.
The topological sorting is not yet fully implemented because we would
like to use graphlib.TopologicalSorter which is not available in
python-2, which we still care about.
Note that, when the order is otherwise unspecified, the plug-ins are
sorted alphabetically by their names.  This is an observable change
in behavior, compared to how it worked before.
=> csmock: do not hard-wire ordering of plug-ins

py/csmock
... so that plug-ins can specify custom package repositories to install tools from.
=> csmock: handle props.add_repos in try_install()

py/csmock
... when interpreted by python-3.9+.  For older releases of python keep
the previous lame implementation as a fallback.  The resulting order of
plug-ins has slightly changed.
Before:
divine, strace, symbiotic, valgrind, bandit, cbmc, clang, coverity, cppcheck, gcc, pylint, shellcheck, smatch
After:
bandit, cbmc, clang, coverity, cppcheck, divine, valgrind, symbiotic, strace, pylint, shellcheck, smatch, gcc
=> csmock: implement topological sort in PluginManager

py/plugins/cbmc.py, py/plugins/divine.py, py/plugins/symbiotic.py
... so that we can spot errors in our converters more easily.  And fail if the conversion fails too.
=> plugins: do not pass `--quiet` to `csgrep` for CBMC, Divine and Symbiotic

make-srpm.sh
The cbmc plug-in took care of installing cbmc-utils into buildroot
(mainly to make csexec work).  However its filter_hook() runs on the
host and uses cbmc-convert-output, which is provided by cbmc-utils.
Hence we need cbmc-utils installed also on the host.
Reported-by: Jerry James
Closes: https://github.com/csutils/csmock/pull/46
=> make-srpm.sh: make cbmc plug-in require cbmc-utils

py/plugins/divine.py
* `--lart stubs` - Transform all undefined functions into stubs, e.g. Divine will fail if a call to such function is reachable.  Previously, Divine even refused to start if any (e.g. unreachable) undefined function was present in the module.
* `-o exit:ignore` - Do not classify non-zero exit code as an error.
=> divine: tweak arguments passed to Divine

py/plugins/divine.py
... to fix unnecessary build failure of findutils-4.8.0-4.fc35:
```
26: In file included from /builddir/build/BUILD/findutils-4.8.0/lib/fdleak.c:25: <--[dioscc]
26: In file included from /usr/include/poll.h:1: <--[dioscc]
26: In file included from /usr/include/sys/poll.h:22: <--[dioscc]
26: In file included from /usr/include/features.h:512: <--[dioscc]
26: /usr/include/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found <--[dioscc]
26: # include <gnu/stubs-32.h>
26:           ^~~~~~~~~~~~~~~~
```
Unfortunately, the build fails with many unrelated errors anyway.
=> divine: optionally require `glibc-devel(x86-32)`

py/plugins/symbiotic.py
Otherwise symbiotic may run for a couple of minutes despite we invoke csmock with `--symbiotic-timeout` set to a couple of seconds.
=> symbiotic: set timeout also for sbt-inst and slicer

scripts/chroot-fixups/symbiotic-timeout.sh
Make sure that symbiotic uses the system-provided timeout(1) for itself.
Otherwise, when formally verifying the coreutils RPM package by Symbiotic,
the test-suite puts our instrumented binary of timeout(1) into ${PATH},
causing it to recursively invoke whole symbiotic on each invocation of
timeout within symbiotic.
=> symbiotic: patch symbiotic to use /usr/bin/timeout

py/csmock
... rather than copying the binaries from the host.  csexec built for
the target environment may have additional features (e.g. the --argv0
option of ld.so) that are not available in the host environment.
=> csmock: install csexec into chroot from Fedora/EPEL

py/plugins/divine.py
Divine will not report calls to undefined functions as an fatal error.
=> divine: pass `-o ignore:notimplemented` to Divine

py/plugins/cbmc.py, py/plugins/divine.py, py/plugins/symbiotic.py
... to make this consistent across all csmock plug-ins
=> cbmc,divine: use 30s timeout by default

py/csmock
If we run `mock --install csdiff compat-openssl11` and `compat-openssl11` is not available, it results in a failed transaction and none of them is installed.
If we run `mock --install` for each package separately, it will install everything that is possible to install.  `mock --install --skip-broken` would be more efficient but it is not available.
=> csmock: install optional pkgs one by one

.github/dependabot.yml, .github/workflows/differential-shellcheck.yml
Differential ShellCheck is a GitHub action that performs differential ShellCheck scans on files changed via PR and reports results directly in PR.
Since this repository contains some shell scripts I think you might find it useful.
Documentation is available at: [@redhat-plumbers-in-action/differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme). Let me know If you are missing some feature or setting.
/cc @kdudka
=> Add Shell linter - Differential-ShellCheck

make-srpm.sh, py/plugins/gitleaks.py
Gitleaks reports too many warnings on certain packages, which wastes resources for no good reason.  Implement warning rate limiting in the filter hook to make the further processing of results less expensive.
Resolves: https://github.com/csutils/csmock/issues/98
Requires: https://github.com/csutils/csdiff/pull/119
Closes: https://github.com/csutils/csmock/pull/100
=> gitleaks: implement --gitleaks-rate-limit defaulting to 1024

py/csmock
Some source tarballs contain a huge number of files and the verbose output of tar unnecessarily pollutes `scan.log`.
=> csmock: be less verbose while extracting source tarballs

make-srpm.sh, py/plugins/gitleaks.py
=> consume csgrep changes to support a new option: limit-msg-len (OSH-67)

make-srpm.sh
The `bld2repo` executive is being used, but corresponding package
`modulemd-tools` was not declared as a dependency earlier.
=> Fix missing dependency

py/plugins/cppcheck.py, py/plugins/gitleaks.py, py/plugins/snyk.py
Otherwise, it is unclear which plug-in actually failed the scan:
```
[...]
>>> 2023-09-14 15:21:46	"'/usr/bin/mock' '-r' 'rhel-8.7.0.z-x86_64' '--plugin-option=tmpfs:keep_mounted=True' '--config-opts=print_main_output=True' '--quiet' '--shell' 'rpm -qa' | sort -V > /tmp/csmocktfv6f2ww/output/debug/rpm-list-mock.txt"
>>> 2023-09-14 15:21:48	"'/usr/bin/mock' '-r' 'rhel-8.7.0.z-x86_64' '--plugin-option=tmpfs:keep_mounted=True' '--config-opts=print_main_output=True' '--quiet' '--shell' 'rpm -qa --provides' | sort -V > /tmp/csmocktfv6f2ww/rpm-list-mock-provides.txt"
>>> 2023-09-14 15:21:50	"tar -cP '/usr/share/csmock/scripts' '/usr/bin/cswrap' '/usr/lib64/cswrap' '/usr/bin/csclng' '/usr/lib64/csclng' '/usr/bin/csclng++' '/usr/bin/cscppc' '/usr/lib64/cscppc' '/usr/share/cscppc' …
```
=> plugins: report an error if the version hook fails

py/common/results.py, py/common/util.py, py/csmock
=> csmock: export functions that can be reused by cspodman

py/csmock
If `csgrep` fails to run in the host environment, it is not clear from the log how the failing command looked like, as for example:
```
[...]
>>> 2023-09-25 11:14:00	"'/usr/bin/mock' '-r' 'default' '--plugin-option=tmpfs:keep_mounted=True' '--config-opts=print_main_output=True' '--quiet' '--shell' 'tar -c --remove-files '/builddir/cswrap-capture.err'' | tar -xC '/tmp/csmock09j0zm72/units-2.17-5.el8/debug/raw-results'"
tar: Removing leading `/' from member names
csgrep: symbol lookup error: csgrep: undefined symbol: _ZNK5boost15program_options22error_with_option_name23substitute_placeholdersERKSs
csgrep: symbol lookup error: csgrep: undefined symbol: _ZNK5boost15program_options22error_with_option_name23substitute_placeholdersERKSs
!!! 2023-09-25 11:14:01	error: failed to pick cswrap …
```
=> csmock: log the command that applies props.cswrap_filters

py/common/results.py
... if any filters of important results are defined.
The full results are now available with the `-all` suffix.  The files with `-imp` suffix are provided as symlinks to the filtered results for compatibility.
Resolves: https://issues.redhat.com/browse/OSH-299
=> common: present important results by default

py/plugins/snyk.py
Related: https://issues.redhat.com/browse/OSH-288
=> snyk: define all findings with level `error` as important

py/common/results.py
The code was trying to create them twice by mistake.  The second creation failed, so it was harmless but it unnecessarily polluted `scan.log` like this:
```
[...]
>>> 2023-09-27 18:12:14 "ln" "-s" "scan-results.err" "/tmp/cspodmanfx586tbu/prom-label-proxy-container-v4.1.8-201907241243/scan-results-imp.err"
>>> 2023-09-27 18:12:14 "ln" "-s" "scan-results.html" "/tmp/cspodmanfx586tbu/prom-label-proxy-container-v4.1.8-201907241243/scan-results-imp.html"
>>> 2023-09-27 18:12:14 "ln" "-s" "scan-results-summary.txt" "/tmp/cspodmanfx586tbu/prom-label-proxy-container-v4.1.8-201907241243/scan-results-imp-summary.txt"
>>> 2023-09-27 18:12:14 "csgrep --mode=grep --invert-match --event \"internal warning\" --prune-events=1 '/tmp/cspodmanfx586tbu/prom-label-proxy-container-v4.1.8-201907241243/debug/sup …
```
=> common: create the compatibility `-imp` symlinks only once

make-srpm.sh
Fixes the following error on minimal OSH worker installations:
```
<<< 2023-10-09 13:27:08	csmock exit code: 0
/bin/sh: line 1: xz: command not found
tar: /tmp/tmpa05fux7j/units-2.21-5.fc37.tar.xz: Wrote only 4096 of 10240 bytes
tar: Child returned status 127
tar: Error is not recoverable: exiting now
!!! 2023-10-09 13:27:08	fatal error: failed to write '/tmp/tmpa05fux7j/units-2.21-5.fc37.tar.xz', not removing '/tmp/csmockbyw9qj7l'...
```
=> packaging: add `tar` and `xz` to `Requires`

py/plugins/snyk.py
Fix: https://issues.redhat.com/browse/OSH-329
Reproducer: csmock -r fedora-rawhide-x86_64 -t snyk -o /tmp/tmp_yvvqrnh/attache.tar.xz  --gcc-analyze --unicontrol-notests --unicontrol-bidi-only --shell-cmd=:'/tmp/tmp_yvvqrnh/attache.tar.gz'
Attache needs to be downloaded from: https://github.com/RedHatInsights/attache
If no supported project is detected using the snyk plugin, it no longer crashes but it does return 0.
=> csmock-snyk-plugin: no supported projects fix

py/plugins/snyk.py
... on successful scans.  This commit fixes a major regression introduced by the previous commit.
Fixes: commit e8863429bd61fd5308547b084c14f23ac8432c58
Related: https://issues.redhat.com/browse/OSH-329
Resolves: https://issues.redhat.com/browse/OSH-362
=> snyk: do not throw away Snyk results by mistake

py/plugins/snyk.py
... to match the file names used by cspodman.  It is utterly confusing for users and developers of csmock and cspodman if each tool uses different file names for the same things.
This divergence somehow slipped through the reviews on cspodman, which implemented the support for Snyk later.  This commit makes it consistent again.
Closes: https://github.com/csutils/csmock/pull/134
=> snyk: unify the names of intermediate files

py/common/results.py
Real-time signals are in the range 32..64 and regular signals below that range.  If an exit code is above `128 + 64 = 192`, it does not denote a terminating signal.
When Snyk code crashes, it returns exit code 255, which should not be handled as termination by a signal:
```
!!! 2023-10-20 13:12:09	fatal error: caught signal 127
```
Related: https://issues.redhat.com/browse/OSH-368
=> results: do not treat exit codes above 192 as fatal

py/csmock
The code that extracts package name from the `name-version-release` string did not work as expected if the `-release` part was missing. Consequently, it did not find the corresponding `exclude-paths.txt` file in the known-false-positives while scanning a source code tarball named: `RedHatInsights-compliance-backend-bd2b8accb3d4aae88a8c1a71563ec3f5ead7b1fa.tar.gz`
Resolves: https://issues.redhat.com/browse/OSH-392
=> csmock: make kfp work for pkgs without the `-release` suffix

make-srpm.sh, py/common/results.py
Tagging important findings does not make sense in the list of important findings only.
Resolves: https://issues.redhat.com/browse/OSH-343
Depends-on: https://github.com/csutils/csdiff/pull/149
=> results: reset imp flag in the list of important findings only

.pylintrc, py/plugins/gitleaks.py, py/plugins/infer.py
Many lines in existing code are longer than 100 chars and attempts to shorten them provoked by pylint usually result in less readable code.
=> lint: set `max-line-length=130` for pylint

py/plugins/gcc.py
The previous solution was not compatible with other compilers, e.g `clang` where the given plugin is called `annobin-clang`.
=> gcc: properly disable annobin for RPM packages

py/plugins/snyk.py
Users are now able to use the introduced flag to pass new parameters to the snyk cli
Resolves: https://issues.redhat.com/browse/OSH-307
csmock -t snyk --snyk-code-test-opts="--report --project-name=osbuild" -r rhel-8-x86_64 osbuild-99-1.el10+1.src.rpm
=> snyk-plugin: added --snyk-code-test-opts flag

py/csmock
... to eliminate the following warning on Fedora 39:
```
% csmock -l
/usr/bin/csmock:180: SyntaxWarning: invalid escape sequence '\.'
m = re.match("^.*/(.*\.module\\+el.*)\\.src\\.rpm$", srpm)
coverity        Proprietary static analyzer providing good signal-to-noise ratio for multiple programming languages.
gcc             Plugin capturing GCC warnings, optionally with customized compiler flags.
```
Reported-by: Lukáš Zaoral
Closes: https://github.com/csutils/csmock/pull/143
=> csmock: fix insufficient regex escaping in extra_build_repos()

py/csmock
... because it is used by `csmock` itself while copying files into chroot.  This commit fixes the following failure with `--no-scan`:
```
$ csmock -r rhel-8.9.0.z-x86_64 --use-host-cppcheck -o output.tar.xz
[...]
>>> 2023-12-11 10:12:01	"tar -cP '/usr/share/csmock/scripts' '/usr/bin/cswrap' '/usr/lib64/cswrap' '/usr/bin/csclng' '/usr/lib64/csclng' '/usr/bin/csclng++' '/usr/bin/cscppc' '/usr/lib64/cscppc' '/usr/share/cscppc' '/usr/bin/cppcheck' '/usr/share/Cppcheck' '/usr/bin/csgcca' '/usr/lib64/csgcca' '/tmp/csmockvujta3wk/gitleaks' | '/usr/bin/mock' '-r' 'rhel-8.9.0.z-x86_64' '--plugin-option=tmpfs:keep_mounted=True' '--config-opts=print_main_output=True' '--quiet' '--shell' 'tar -xC/'"
/bin/sh: tar: command not found
scan.ini: analyzer-version-clang = 16.0.6
!!! 2023-12-11 10:12:05 …
```
=> csmock: make sure that `tar` is installed in chroot

py/common/results.py
... that are tagged important by both a csmock plug-in and the scanner itself.  In a scan of `gcc-toolset-12-gcc-12.2.1-7.4.el9` we had more important findings than all findings, which does not really make any sense:
```
% grep RESOURCE_LEAK gcc-toolset-12-gcc-12.2.1-7.4.el9/scan-results-imp-summary.txt
2 RESOURCE_LEAK                                           error[too-many]
2046 RESOURCE_LEAK                                           leaked_storage
756 RESOURCE_LEAK                                           overwrite_var
% grep RESOURCE_LEAK gcc-toolset-12-gcc-12.2.1-7.4.el9/scan-results-all-summary.txt
1 RESOURCE_LEAK                                           error[too-many]
1023 RESOURCE_LEAK                                           leaked_storage
378 RESOURCE_LEAK …
```
=> results: do not duplicate important findings

py/common/results.py
... to make it obvious in `scan.log` that they did not affect the overall exit code.
=> results: print `warning` for recoverable errors

py/common/results.py
This allows comments in the path exlusion regex file. Instead of adding each line as a filtering rule, it skips empty lines and lines starting with a # symbol.
Fixes https://issues.redhat.com/browse/OSH-508
=> results: skip comments in exclude-paths.txt

py/csmock
... to pass `--scrub=all` to the underlying `mock` instance.
Related: https://github.com/openscanhub/openscanhub/pull/228#discussion_r1494707783
=> csmock: add `--scrub-on-exit` option

py/csmock
To fix a crash when two mock profile configuration files have different names but use the same root directory:
```
[...]
>>> 2024-02-19 14:29:12	"/usr/bin/mock" "-r" "/tmp/tmpyfvruenl/mock.cfg" "--plugin-option=tmpfs:keep_mounted=True" "--config-opts=print_main_output=True" "--init"
INFO: mock.py version 5.2 starting (python version = 3.9.18, NVR = mock-5.2-1.kdudka.5.el9), args: /usr/libexec/mock/mock -r /tmp/tmpyfvruenl/mock.cfg --plugin-option=tmpfs:keep_mounted=True --config-opts=print_main_output=True --init
Start(bootstrap): init plugins
INFO: selinux enabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
Start: clean chroot
ERROR: Build root is locked by another process.
!!! 2024-02-19 14:29:13 …
```
=> csmock: use the root mock profile property for lock names

py/CMakeLists.txt, py/common/snyk.py, py/plugins/snyk.py
Related: https://issues.redhat.com/browse/OSH-347
Reproducer: csmock -t snyk --force -r rhel-8-x86_64 osbuild-106-1.el10+4.src.rpm
Added the stats from snyk results (snyk coverage rate, analyzed files and total of files) to the metadata file.
=> snyk: added snyk stats to metadata

py/plugins/snyk.py
Reproducer: csmock -r rhel-9-x86_64 -t snyk -f octavia-amphora-image-vert-fips-x86_64-18.0-20240305.1.el9ost.src.rpm
Related: https://issues.redhat.com/browse/OSH-583
When an snyk-unsupported project is scanned using snyk, no stats are generated.
=> snyk: skip writing of scan metadata when no supported project

py/plugins/gcc.py
New versions of GCC started to produce ASCII art, which is not properly handled by the plain-text parser in csdiff:
```
Error: GCC_ANALYZER_WARNING (CWE-126): [#def1]
bluez-5.75/emulator/bthost.c: scope_hint: In function ‘queue_command’
bluez-5.75/emulator/bthost.c:571:52: warning[-Wanalyzer-out-of-bounds]: stack-based buffer over-read
bluez-5.75/emulator/bthost.c:571:52: note: read of 8 bytes from after the end of ‘iov’
bluez-5.75/emulator/bthost.c:571:52: note: valid subscripts for ‘iov’ are ‘[0]’ to ‘[2]’
```
If gcc in the chroot recognizes `-fdiagnostics-text-art-charset=none`, use it to prevent GCC analyzer from producing such output.
Reported-by: David Malcolm
=> gcc: eliminate misaligned ASCII art coming from GCC analyzer

py/common/results.py
... rather than clearing it.  If scan results are processed later on, it is useful to know the original state of the "imp" flag, regardless of the context (whether we have a list of important findings only, or an all-in-one list of findings).  A side effect will be that a red `[important]` tag will appear in the HTML output next to each finding, which is probably harmless.
Related: https://issues.redhat.com/browse/OSH-343
Related: https://issues.redhat.com/browse/OSH-565
=> results: set the "imp" flag in the list of important findings

py/csmock
... while scaning tarballs instead of SRPMs:
```
$ csmock -r fedora-rawhide-x86_64 -t clippy --shell-cmd='cargo build' -f trustification-main.tar.gz
[...]
+ cargo build
+ set -- clippy
+ /usr/bin/cargo_original clippy --message-format=json
/usr/bin/cargo: line 9: /builddir/clippy-output.txt: Permission denied
+ /usr/bin/cargo_original build
Updating git repository `https://github.com/ctron/csaf-rs`
error: failed to load source for dependency `csaf`
Caused by:
Unable to update https://github.com/ctron/csaf-rs?rev=183326beac525d58962f78be8eca973017702753#183326be
Caused by:
failed to create directory `/builddir/.cargo/git/db/csaf-rs-27cd9c29798421c8`
Caused by:
Permission denied (os error 13)
Finish: chroot ['/bin/su mockbuild -l -c "PATH=\\$PATH sh -c \\"sh -x …
```
=> csmock: fix Permission denied errors on /builddir

py/plugins/snyk.py
... in the chroot.  Otherwise, it is going to fail.
Related: https://issues.redhat.com/browse/OSH-69
=> snyk: explicitly enable networking for snyk client execution

make-srpm.sh, scripts/chroot-fixups/00-pre-usr-move-shells.sh
When we build csmock for RHEL-9, rpmbuild translates `/bin/bash` to `/usr/bin/bash` in our scripts.  When we copy the scripts into an old chroot, such as `rhel-6-x86_64`, the translated path does not exist and the script fails with:
```
>>> 2024-05-20 12:04:36	"/usr/bin/mock" "-r" "rhel-6-x86_64" "--plugin-option=tmpfs:keep_mounted=True" "--config-opts=print_main_output=True" "--quiet" "--chroot" "/usr/share/csmock/scripts/run-shellcheck.sh /builddir/build/BUILDROOT > /builddir/shellcheck-capture.err"
/bin/sh: /usr/share/csmock/scripts/run-shellcheck.sh: /usr/bin/bash: bad interpreter: No such file or directory
```
=> chroot-fixups: make our scripts work again in pre-UsrMove chroots

py/csmock
Make the code obtaining package name recognize a full-size SHA1 hash encoded in lowercase as the `version` part, too.
=> csmock: make kfp work for project-koku-koku-cbe5e5c3355c1e140aa1cca7377aebe09d8d8466

make-srpm.sh, py/plugins/clippy.py, scripts/convert-clippy.py
this is a follow up to https://github.com/csutils/csmock/pull/157
=> rust-clippy: fixes

scripts/inject-clippy.sh
... so that we can successfully scan the Rust code in `librsvg2-2.50.7-1.el9_0` where `cargo` is invoked like this:
```
cd ./librsvg && \
PKG_CONFIG_ALLOW_CROSS=1 \
PKG_CONFIG='/usr/bin/x86_64-redhat-linux-gnu-pkg-config' \
CARGO_TARGET_DIR=/builddir/build/BUILD/librsvg-2.50.7/target \
cargo --locked build --verbose  --release \
&& cd /builddir/build/BUILD/librsvg-2.50.7 && /bin/sh ./libtool [...]
```
Related: https://issues.redhat.com/browse/OSH-30
=> clippy: make the wrapper work if `build` is not the 1st arg

scripts/inject-clippy.sh
It turned out that the last change was not properly tested.
The previously used syntax is not recognized by bash:
```
[...]
cd ./librsvg && \
PKG_CONFIG_ALLOW_CROSS=1 \
PKG_CONFIG='/usr/bin/pkg-config' \
CARGO_TARGET_DIR=/builddir/build/BUILD/librsvg-2.50.7/target \
cargo --locked build --verbose  --release \
&& cd /builddir/build/BUILD/librsvg-2.50.7 && /bin/sh ./libtool  --tag=CC   --mode=link gcc  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=forma
/usr/bin/cargo: line 5: ${@[i]}: bad substitution
[...]
```
This commit fixes it.  Moreover, the invocation of `cargo_original` was
wrong because the wrapper path was passed as the first command-line arg
by mistake:
```
[...]
cd ./librsvg &&                     \
PKG_CONFIG_ALLOW_CROSS=1 …
```
=> clippy: make the cargo wrapper work in bash

py/csmock
... and not `Path.stem` which also removes a filename suffix.
Fixes: b2c720159d52ac89e10e290237f230dbe41848a8 ("csmock: use the root mock profile property for lock names")
Resolves: https://issues.redhat.com/browse/OSH-464
=> csmock: use `Path.name` to get the basename

scripts/inject-clippy.sh
... to avoid triggering a non-fatal failure while exporting files from the chroot in case Clippy is enabled for a non-Rust project:
```
tar: /builddir/clippy-output.txt: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```
Related: https://issues.redhat.com/browse/OSH-30
=> clippy: always create the capture file for Clippy

py/plugins/clippy.py
If the `clippy` package is not available in the build repos, a warning
is emitted and `clippy` is not recorded as an enabled tool in the scan
properties.  But the scan continues without `clippy` in this case.
The approach is similar to what `--gcc-analyze` does.  This is needed
because `clippy` is not available for each mock config and we do not
want to configure the set of enabled tools separately for each mock
config.
Related: https://issues.redhat.com/browse/OSH-30
=> clippy: do not fail the scan if clippy fails to install

py/csmock
... when execution of tests is not needed for the requested scan. This fixes an unnecessary failure while SAST scanning `jss-4.9.4-1.module+el8.7.0+15532+95bac9ee`
Resolves: https://issues.redhat.com/browse/OSH-697
Closes: https://github.com/csutils/csmock/pull/176
=> csmock: use `NOCHECK_RPM_OPTS` also for `%build`

cwe-map.csv
... that causes a parsing error and prevents GitHub from rendering the page properly.
Fixes: commit c4cecc307723f0bf925c88dcd51ae3a311ff784f
=> cwe-map.csv: fix a misplaced quote

scripts/chroot-fixups/rpm-build-scripts.sh
The `brp-llvm-compile-lto-elf` script does not work well in our scanning environment and causes the %install section of `llvm-16.0.6-4.el9` to take 7 days to complete.
Depends-on: https://github.com/csutils/csmock/pull/179
=> chroot-fixups: prevent `%install` of llvm from taking ages to complete

py/plugins/cppcheck.py
```
Error: CPPCHECK_WARNING: [#def1]
units-2.22/getopt.c: information[normalCheckLevelMaxBranches]: Limiting analysis of branches. Use --check-level=exhaustive to analyze all branches.
Error: CPPCHECK_WARNING: [#def2]
units-2.22/parse.tab.c: information[normalCheckLevelMaxBranches]: Limiting analysis of branches. Use --check-level=exhaustive to analyze all branches.
```
=> cppcheck: suppress information[normalCheckLevelMaxBranches] reports

py/common/results.py
... by using `shlex.quote()` from standard Python library.  This bug caused regular expressions with parentheses to be interpreted by shell:
```
/bin/sh: -c: line 1: syntax error near unexpected token `('
```
Also avoid using the open-coded `shell_quote()` function from `util.py` while printing shell commands in `exec_cmd()` because the function is rather problematic and should be eventually unimplemented.
Unfortunately, we cannot easily nest `shlex.quote()` while combining `mock --chroot ...` with `su -c ...` and the like because it results in totally unreadable `scan.log`.
Resolves: https://issues.redhat.com/browse/OSH-617
=> results: fix quoting in `handle_known_fp_list()`

py/csmock, py/plugins/shellcheck.py, scripts/run-shellcheck.sh, tests/simple_build/shellcheck.fmf, tests/simple_build/test.sh
... initially developed for Konflux CI.  The updated version runs more processes of `shellcheck` in parallel, each of them with a strictly set timeout (by default 30s of wall-clock time).
Related: https://issues.redhat.com/browse/OSH-655
Resolves: https://issues.redhat.com/browse/OSH-733
=> shellcheck: use a new version of `run-shellcheck.sh`

make-srpm.sh
... so that one can easily install the `run-shellcheck.sh` script without unnecessary dependencies on `mock` etc.
Related: https://issues.redhat.com/browse/OSH-738
=> packaging: create the plugin-shellcheck-core subpackage

py/csmock
... instead of "defects" in the downstream patches reports.
Related: https://github.com/openscanhub/openscanhub/issues/297
=> Use the term "findings"

py/common/util.py, py/csmock, py/plugins/bandit.py, py/plugins/pylint.py, py/plugins/shellcheck.py
The `%{buildroot}` directory we were looking into is no longer used by new versions of `rpm`.  The directory was moved with the following backward-incompatible change: https://github.com/rpm-software-management/rpm/commit/9d35c8df497534e1fbd806a4dc78802bcf35d7cb
This commit makes csmock look into both the locations.
Fixes: https://github.com/csutils/csmock/issues/191
=> csmock: support buildroot location used by new `rpm`

py/csmock, py/plugins/cppcheck.py
See the individual commit messages for details.
Resolves: https://github.com/csutils/csmock/issues/117
=> improve handling of failed hooks

make-srpm.sh, py/plugins/gcc.py
With https://copr.fedorainfracloud.org/coprs/dmalcolm/gcc-latest/ added to the `fedora-41-x86_64` mock config, this can be tested using the following commands:
```
koji download-build -a src units-2.23-3.fc41
csmock -f units-2.23-3.fc41.src.rpm -r fedora-41-x86_64 --install gcc-latest --gcc-analyzer-bin /opt/gcc-latest/bin/gcc
```
Depends-on: https://github.com/csutils/csdiff/pull/210
Related: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116613
=> gcc: use SARIF output with `--gcc-analyzer-bin`

py/csmock, tests/simple_build/test.sh
RHEL-7 packages do not use dynamic build dependencies and the new way to install build dependencies breaks build/scan in some cases, such as with `ipa-4.6.5-11.el7_7.4`.
Fixes: commit 50b1c8c7b5de0ba8befc832f3b29940524cdb325
Related: https://github.com/csutils/csmock/issues/188
=> csmock: use `--installdeps` for legacy chroots

.github/workflows/differential-shellcheck.yml, scripts/run-shellcheck.sh
Rather than failing the whole scan, record them in the scan results.
Reproducer:
```
csmock -r rhel-7.7.z-x86_64 -f pki-core-10.5.16-7.el7_7.src.rpm -t shellcheck
```
This commit makes the above scan succeed with the following additional finding included in the scan results:
```
Error: SHELLCHECK_WARNING:
/usr/sbin/pki-server-nuxwdog: internal error: hGetContents: invalid argument (invalid byte sequence)
```
=> shellcheck: improve handling of ShellCheck internal errors

.github/workflows/differential-shellcheck.yml
Also, upload the debugging SARIF artifact only when debug is enabled.
Example of difference between ShellCheck display engines: https://github.com/redhat-plumbers-in-action/differential-shellcheck?tab=readme-ov-file#display-engine
=> ci(shellcheck): use `sarif-fmt` as display engine

scripts/run-pylint.sh
... to make it work the same way as `run-shellcheck.sh` works now.
Given the fact that `pylint` is not enabled by default, the `run-pylint.sh` script has not been actively maintained.  This commit transfers the well-tested parts of code from `run-shellcheck.sh` to `run-pylint.sh`.
=> pylint: modernize the `run-pylint.sh` script

py/csmock
... introduced by newer versions of RPM in Fedora.  This is needed for previously recorded known-false-positives to work because they would not be matched with file paths like this (see the duplicated version string in the first two directory levels):
```
util-linux-2.42.start-build/util-linux-2.42.start/disk-utils/cfdisk.c:875:28: warning[-Wanalyzer-malloc-leak]: leak of ‘*m.ignore’
```
=> csmock: revert differences in source file paths

csmock/csmock
Related: https://github.com/csutils/csmock/pull/195
PR: https://github.com/csutils/csmock/pull/204
=> csmock: use `--installdeps` for rhel-6, too

csmock/csmock
During a csmock run, there are two uses of `rpm -Uvh <srpm>` which install the sources into the build dir. The first runs as mockbuild user, whilst the second ran as root. This second run installed files owned by root, which could prevent some file operations performed during the rpm build from succeeding.
PSSECAUT-1201
=> csmock: install SRPM as mockbuild user

.github/workflows/coverity.yml
Commit 2a9ee594097042a784289c41b2e9522ebe6de39c fixed the CI failure. Nevertheless the Coverity service still sends failure notifications about incomplete capture.  Explicitly specify the programming language to eliminate these failure notifications.
Also extend the trigger for this workflow to a branch named `coverity` so that we can esily test changes in the CI configuration by pushing updates to the upstream `coverity` branch.
Related: https://github.com/csutils/csmock/issues/207
=> CI: specify the programming language for Coverity
